const CONSTANTS = {
  CANVAS_WIDTH: 800,
  CANVAS_HEIGHT: 600,
  PADDLE_WIDTH: 10,
  PADDLE_HEIGHT: 80,
  PADDLE_SPEED: 6,
  PADDLE_MARGIN: 20,
  BALL_RADIUS: 6,
  BALL_INITIAL_SPEED: 4,
  BALL_SPEED_INCREMENT: 0.2,
  BALL_MAX_SPEED: 10,
  TICK_RATE: 60,
  TICK_INTERVAL: Math.round(1000 / 60),
  SCORE_PAUSE_MS: 1500,
  COUNTDOWN_MS: 3000,
  LEADERBOARD_SIZE: 10,
};

module.exports = CONSTANTS;
